export const PageURL = {
  Login: "/login",
  Register: "/register",
  Forgot: "/forgot",
  Reset: "/reset-password",
  Feed: "feed",
  Friends: "friends",
  Events: "events",
  WatchVideos: "watch-videos",
  Notification: "notifications",
  Photos: "photos",
  FRIENDS: "friends",
  Messanger: "messanger",
  Marketplace: "marketplace",
  Profile: "u",
  NotFound: "*",
};
